services:
  app:
    container_name: "backcontainer"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysqldb:3306/agriario_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    container_name: "mysqldb"
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "agriario_db"
      MYSQL_USER: "migue"
      MYSQL_PASSWORD: "migue"
      MYSQL_ROOT_PASSWORD: "root"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:
    external: false
